### ISSUE TITLE
Move the default database dir to $HOME

### ISSUE THREAD

**Issue by 5chdn** [ethereum/ethereumj#418]
Hi, wouldn't it be wise to move the default database dir to the user's `$HOME`?

I recently cleaned up my workspace and today I wanted to run EthereumJ and I noticed, I also deleted the git clone of ethereumj on my disk. Last time I did not set any database dir path (now I'm aware of that feature), however, with the deletion of the whole source code I also removed the whole blockchain database.

Please comment, isn't it a good idea to use, for instance, `~/.ethereumj/database` as default?

**Comment by Nashatyrev** [comment]
We are releasing Harmony soon (aka EtherumJ node), it might be wise to apply your suggestion there. @cupuyc what do you think?
For the pure core library I don't think that makes sense since it's not a final application and it's up to EthereumJ users to choose the right options. For development it's more comfortable I suppose to keep the DB nearby each workspace (you may have several projects which are using EthJ)

**Comment by cupuyc** [comment]
I agree with Anton, that database should be near workspace.

In [Harmony](https://github.com/ether-camp/ethereum-harmony) we included your suggestion and storing database at user home.

**Comment by Nashatyrev** [comment]
Ok, then I'm closing this
