### ISSUE TITLE
Implement contract events (LOG) API

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#421]
We are lacking of convenient LOG tracking API. It is currently implemented as JSON RPC filters, but we need to add this as Java API

**Comment by ajunge** [comment]
I'm trying to capture contract events. Is there a sample of how to do it with JSON RPC now?

**Comment by arass** [comment]
Anyone working on this? I could give this a try (once Morden is working again).

**Comment by btiernay** [comment]
Curious about this as well.

**Comment by btiernay** [comment]
What would be great is a way to supply the ABI and parse into something like a `JsonNode`. This would be similar in function to http://ethereum.stackexchange.com/questions/1381/how-do-i-parse-the-transaction-receipt-log-with-web3-js

**Comment by arass** [comment]
I was thinking more high level.
Constructor based on type of search, maybe? Builder pattern?
Constructor (contract_address).method("inc").blocking(true).build();
If blocking is enabled - it will block on next(), so that it's an infinite loop (exit via Inerrupted exception, or allow for a blocking timeout (both)).

Then something as simple to use as an Iterable interface, perhaps?
Then you can do:
for (T t : contractEvents)
         myCode(t);

T can be whatever internal datatype we get from API. Avoids overhead in converting data.

**Comment by adridadou** [comment]
I've done something about that on github.com/adridadou/eth-contract-api 
Where you can register a watcher on Events and they are converted into a type you have defined. 
If it helps ..

**Comment by mkalinin** [comment]
PR https://github.com/ethereum/ethereumj/pull/984
