### ISSUE TITLE
Build from sources failed 3 tests. 

### ISSUE THREAD

**Issue by CSPRNG** [ethereum/ethereumj#905]
I tried to build ethereumj using github and the listed instructions; but it failed some tests.

 the listed instructions are the first steps Importing project to IntelliJ IDEA here: 
 https://github.com/ethereum/ethereumj

git clone https://github.com/ethereum/ethereumj
cd ethereumj/
./gradlew build

IDEA:
    File -> New -> Project from existing sources…
    Select ethereumj/build.gradle
    Dialog “Import Project from gradle”: press “OK”
    After building run either org.ethereum.Start, one of org.ethereum.samples.* or create your own main.

------------------------------------------------------------------------------
Here only the lines showing tests that failed:

org.ethereum.core.genesis.GenesisLoadTest > shouldLoadGenesisFromFile_whenBothSpecified FAILED
    java.lang.RuntimeException at GenesisLoadTest.java:164

org.ethereum.core.genesis.GenesisLoadTest > shouldLoadGenesis_whenFullPathSpecified FAILED
    java.lang.RuntimeException at GenesisLoadTest.java:164

org.ethereum.util.ByteUtilTest > testIpConversion FAILED
    org.junit.ComparisonFailure at ByteUtilTest.java:497

979 tests completed, 3 failed, 104 skipped
:ethereumj-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ethereumj-core:test'.
BUILD FAILED

**Comment by MarkKlein1** [comment]
These 2 errors are caused by a path with a directory name that contains a space:
org.ethereum.core.genesis.GenesisLoadTest > shouldLoadGenesisFromFile_whenBothSpecified 
org.ethereum.core.genesis.GenesisLoadTest > shouldLoadGenesis_whenFullPathSpecified 
This issue is tricky because it is OS dependent (I am using Mac OS 10.12)
I Just renamed the directory removing the space and it works; but perhaps the code should be improved so it works in all cases.

The  error in org.junit.ComparisonFailure at ByteUtilTest.java:497 is caused when the ip number is out of expected range:

The code is malfunctioning when the test ip is "255.255.255.256" but it works when the test ip is "255.255.255.255" . 

        String ip3 = "255.255.255.255"; // this test works fine
        byte[] ip3Bytes = ByteUtil.hostToBytes(ip3);
        assertEquals(ip3, ByteUtil.bytesToIp(ip3Bytes));

        // Fallback case
        String ip4 = "255.255.255.256"; // this test fails
        byte[] ip4Bytes = ByteUtil.hostToBytes(ip4);
        assertEquals("0.0.0.0", ByteUtil.bytesToIp(ip4Bytes));  

The assertEquals above is obviously going to fail.., it returns:
expected:<[0.0.0.0]> but was:<[62.138.239.45]>
This ip number <[62.138.239.45]> is wrong regardless.
